name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-20.04, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Windows 🪟 dependencies
        run: vcpkg install freetype:x64-windows glew:x64-windows sdl2:x64-windows glm:x64-windows
        if: matrix.os == 'windows-latest'

      - name: Install macOS 🍎 dependencies
        run: brew install glew sdl2 glm
        if: matrix.os == 'macOS-latest'

      - name: Install Ubuntu 🐧 dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt-get install build-essential libxmu-dev libxi-dev libgl-dev libglew-dev libsdl2-dev libglm-dev

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake Windows
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        if: matrix.os == 'windows-latest'

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        if: matrix.os != 'windows-latest'

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.
        run: cmake --build . --config $BUILD_TYPE --target package

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE

      - name: Upload Windows 🪟 package
        uses: actions/upload-artifact@v1
        if: matrix.os == 'windows-latest'
        with:
          name: ngf-0.0.1-win64.zip
          path: ../build/ngf-0.0.1-win64.zip

      - name: Upload Ubuntu 🐧 package
        uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: ngf-0.0.1-linux.zip
          path: ../build/ngf-0.0.1-linux.zip

      - name: Upload macOS 🍎 package
        uses: actions/upload-artifact@v1
        if: matrix.os == 'macOS-latest'
        with:
          name: ngf-0.0.1-osx.zip
          path: ../build/ngf-0.0.1-osx.zip

